gigatron_base_url = "https://gigatron.rs/"
site_tittle = "Gigatron"
site_available_message = "The site is currently accessible."
site_not_available_message = "The site is currently inaccessible."
site_available_message_second_request = "The site is accessible, proceed with the second request."
site_not_available_message_second_request = "The site is inaccessible, cannot proceed with the second request."
article_displayed_successfully_message = "The article is successfully displayed."
article_display_failed_message = "Failed to display the article."
search_url_for_first_page = "https://search.gigatron.rs/v1/search/get?pojam=Monitor&page=true&strana=1"
action_offers_url = "https://api-v2.gigatron.rs/core/news/get/2/1?uid=giga65510d81a49ba4.33483555"

search_box_locator = "#header__center__searchbox > div > div > input[type=text]"
grid_products_locator = "grid-products"
accept_cookie_button = "//*[contains(text(), 'Prihvati neophodne')]"
